# Generated by Django 5.1.1 on 2025-05-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('amid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ambulanceName', models.CharField(max_length=100)),
                ('ambulanceNumber', models.CharField(max_length=20, unique=True)),
                ('ambulanceOrgaName', models.CharField(max_length=50)),
                ('ambulanceDriverName', models.CharField(max_length=60)),
                ('ambulanceDriver2Name', models.CharField(max_length=60, null=True)),
                ('ambulanceDriverNum', models.IntegerField()),
                ('ambulanceDriver2Num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ambulanceCurrentLocation',
            fields=[
                ('curAmb', models.BigAutoField(primary_key=True, serialize=False)),
                ('currLat', models.FloatField()),
                ('currLon', models.FloatField()),
                ('current_Address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notid', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=100)),
                ('notify_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('ambulanceCurrLoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulancecurrentlocation')),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='routeAmbulance',
            fields=[
                ('routAmb', models.BigAutoField(primary_key=True, serialize=False)),
                ('fromDesti', models.CharField(max_length=100)),
                ('toDesti', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
    ]
