# Generated by Django 5.1.1 on 2025-04-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('amid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ambulanceName', models.CharField(max_length=100)),
                ('ambulanceNumber', models.CharField(max_length=20, unique=True)),
                ('ambulanceOrgaName', models.CharField(max_length=50)),
                ('ambulanceDriverName', models.CharField(max_length=60)),
                ('ambulanceDriver2Name', models.CharField(max_length=60, null=True)),
                ('ambulanceDriverNum', models.IntegerField(max_length=12)),
                ('ambulanceDriver2Num', models.IntegerField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='routeAmbulance',
            fields=[
                ('routAmb', models.BigAutoField(primary_key=True, serialize=False)),
                ('fromDesti', models.CharField(max_length=100)),
                ('toDesti', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
    ]
