# Generated by Django 5.1.1 on 2025-05-19 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulanceOrgaDetail',
            fields=[
                ('aonid', models.BigAutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=100)),
                ('is_Gov', models.BooleanField(default=False)),
                ('is_Private', models.BooleanField(default=False)),
                ('organizationContact', models.IntegerField()),
                ('orgaAddress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambulanceOrgaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulanceorgadetail'),
        ),
    ]
