# Generated by Django 5.1.1 on 2025-04-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ambulance_ambulancedriver2num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulanceCurrentLocation',
            fields=[
                ('curAmb', models.BigAutoField(primary_key=True, serialize=False)),
                ('currLat', models.FloatField(max_length=100)),
                ('currLon', models.FloatField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
    ]
