# Generated by Django 5.1.1 on 2025-05-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ambulanceorgadetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='ambulanceDriver2Num',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='ambulanceDriverNum',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambulanceDriver2Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondry_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambulanceDriverName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
