# Generated by Django 5.1.1 on 2025-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ambulancecurrentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancecurrentlocation',
            name='prevLat',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulancecurrentlocation',
            name='prevLon',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
