# Generated by Django 5.1.1 on 2025-04-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ambulancecurrentlocation_prevlat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancecurrentlocation',
            name='prevLat',
        ),
        migrations.RemoveField(
            model_name='ambulancecurrentlocation',
            name='prevLon',
        ),
    ]
