# Generated by Django 5.1.1 on 2025-05-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ambulancecurrentlocation_currlat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notid', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=100)),
                ('notify_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('ambulanceCurrLoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulancecurrentlocation')),
                ('ambulanceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
    ]
