# Generated by Django 5.1.1 on 2025-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='current_Address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
